version: "3"

services:
  db:
    image: "postgres"
    environment:
      POSTGRES_USER: omero
      POSTGRES_DB: omero
      POSTGRES_PASSWORD: omero
    networks:
      - omero
    volumes:
      - "./database:/var/lib/postgresql/data"

  server:
    image: "openmicroscopy/omero-server"
    environment:
      CONFIG_omero_db_host: db
      CONFIG_omero_db_user: omero
      CONFIG_omero_db_pass: omero
      CONFIG_omero_db_name: omero
      ROOTPASS: password
    networks:
      - omero
    ports:
      - "4063:4063"
      - "4064:4064"
    volumes:
      - "./omero:/OMERO"
    depends_on:
      - db

#  web:
#    image: "openmicroscopy/omero-web-standalone"
#    environment:
#      OMEROHOST: server
#    networks:
#      - omero
#    ports:
#      - "4080:4080"

networks:
  omero:
